# Generated by Django 5.2 on 2025-05-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIB', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/profile/'),
        ),
    ]
