# Generated by Django 5.2 on 2025-05-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIB', '0004_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
