# Generated by Django 5.2 on 2025-06-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MIB", "0012_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
